#!/usr/bin/python3

import os
import sys
from django.core.management import execute_from_command_line

if __name__ == '__main__':

	exec_path = os.path.abspath(__file__);
	web_package_path = os.path.abspath(os.path.join(exec_path, '..'))
	workspace_path = os.path.join(web_package_path, '..')
	base_path = os.path.join(workspace_path, '..')
	data_path = os.path.join(base_path, 'Alexdata')
	config_path = os.path.abspath(os.path.join(data_path, 'config.xml'))
	base_package_path = os.path.abspath(os.path.join(workspace_path, 'AlexandriaBase'))
	plugin_package_path = os.path.abspath(os.path.join(workspace_path, 'AlexandriaPlugins'))
	
	os.environ.setdefault("ALEX_CONFIG", config_path)
	sys.path.append(base_package_path)
	sys.path.append(plugin_package_path)
	sys.path.append(web_package_path)
	os.environ.setdefault("DJANGO_SETTINGS_MODULE", "alexandriaweb.settings")

	execute_from_command_line([os.path.join(web_package_path, 'manage.py')] + sys.argv[1:])

